spring.application.name=parsimony2mlf

spring.datasource.url=jdbc:mariadb://localhost:3306/mlf
spring.datasource.username=mlf
spring.datasource.password=trivial
spring.jpa.hibernate.ddl-auto=validate

name.stromkabelsalat.parsimony2mlf.find-tags=false
